"""Executable plugin descriptors, discovery, component protocols, and registry."""

from eegle._domain import ComponentKind, Determinism, EquivalenceLevel, ExecutionMode
from eegle.plugins.contracts import (
    Actuator,
    AuthorizationProvider,
    AdaptiveModel,
    Adapter,
    ArtifactProducer,
    ExecutionContext,
    GraphNode,
    LifecycleComponent,
    Model,
    OutcomeResolver,
    Policy,
    QualityGate,
    Sink,
    Source,
    StatefulComponent,
    Transform,
    WindowBuilder,
)
from eegle.plugins.construction import MaterializedArtifact, ModelConstructionContext
from eegle.plugins.registry import (
    ContractTransformSpec,
    ConstructionAPI,
    PluginCapabilities,
    PluginDescriptor,
    PluginRegistry,
    PortSpec,
    ProcessingOperationBinding,
    StateBehavior,
    validate_component_instance,
)


__all__ = [
    "Actuator",
    "AuthorizationProvider",
    "AdaptiveModel",
    "Adapter",
    "ArtifactProducer",
    "ComponentKind",
    "ConstructionAPI",
    "ContractTransformSpec",
    "Determinism",
    "EquivalenceLevel",
    "ExecutionContext",
    "GraphNode",
    "ExecutionMode",
    "LifecycleComponent",
    "Model",
    "MaterializedArtifact",
    "ModelConstructionContext",
    "OutcomeResolver",
    "PluginCapabilities",
    "PluginDescriptor",
    "PluginRegistry",
    "Policy",
    "PortSpec",
    "ProcessingOperationBinding",
    "QualityGate",
    "Sink",
    "Source",
    "StateBehavior",
    "StatefulComponent",
    "Transform",
    "WindowBuilder",
    "validate_component_instance",
]
