"""Provisional public contracts for researcher-facing experiment authoring.

Phase 7 authoring values are non-executable inputs that lower into the
canonical specifications.  No draft, source map, template, or authoring parser
is a compiler or runtime authority.
"""

from eegle.authoring.contracts import (
    AuthoringOrigin,
    CanonicalArtifact,
    ConfirmationState,
    ScientificMateriality,
    SourceKind,
    SourceLocation,
)
from eegle.authoring.builders import (
    AUTHORING_EXPORT_SCHEMA_ID,
    AUTHORING_PROJECT_SCHEMA_ID,
    AuthoredExperiment,
    ExperimentBuilder,
    WrittenAuthoringProject,
)
from eegle.authoring.drafts import (
    DEPLOYMENT_REQUIREMENTS_SCHEMA_ID,
    DeploymentRequirement,
    DeploymentRequirementKind,
    DeploymentRequirements,
    DraftIssue,
    DraftLoweringError,
    ExperimentDraft,
    LoweredExperiment,
    TemplateSelection,
    UnresolvedChoice,
    UnresolvedKind,
    lower_experiment_draft,
)
from eegle.authoring.provenance import (
    AuthoringProvenance,
    CanonicalTarget,
    DraftSourceMap,
    ProvenanceEntry,
    TemplateReference,
)
from eegle.authoring.templates import (
    BUILTIN_TEMPLATE_CATALOG,
    TEMPLATE_DEFINITION_SCHEMA_ID,
    TEMPLATE_EXPANSION_LOCK_SCHEMA_ID,
    TemplateCatalog,
    TemplateDefinition,
    TemplateExpansion,
    TemplateExpansionLock,
    TemplateMigrationPolicy,
    TemplateParameterTarget,
    TemplateProfile,
    builtin_templates,
    create_template_draft,
    expand_template,
)
from eegle.authoring.schemas import (
    AUTHORING_PROVENANCE_JSON_SCHEMA,
    AUTHORING_PROVENANCE_SCHEMA_ID,
    DEPLOYMENT_REQUIREMENTS_JSON_SCHEMA,
    EXPERIMENT_DRAFT_JSON_SCHEMA,
    EXPERIMENT_DRAFT_SCHEMA_ID,
    TEMPLATE_AUTHORING_JSON_SCHEMA,
    TEMPLATE_AUTHORING_SCHEMA_ID,
    validate_authoring_provenance_payload,
    validate_deployment_requirements_payload,
    validate_experiment_draft_payload,
    validate_template_authoring_payload,
)
from eegle.authoring.yaml import (
    RestrictedYamlError,
    RestrictedYamlLimits,
    load_yaml_experiment,
    parse_yaml_experiment,
    read_yaml_experiment,
)


__all__ = [
    "AUTHORING_PROVENANCE_JSON_SCHEMA",
    "AUTHORING_PROVENANCE_SCHEMA_ID",
    "AUTHORING_EXPORT_SCHEMA_ID",
    "AUTHORING_PROJECT_SCHEMA_ID",
    "BUILTIN_TEMPLATE_CATALOG",
    "AuthoringProvenance",
    "AuthoringOrigin",
    "AuthoredExperiment",
    "CanonicalArtifact",
    "CanonicalTarget",
    "ConfirmationState",
    "DEPLOYMENT_REQUIREMENTS_JSON_SCHEMA",
    "DEPLOYMENT_REQUIREMENTS_SCHEMA_ID",
    "DeploymentRequirement",
    "DeploymentRequirementKind",
    "DeploymentRequirements",
    "DraftIssue",
    "DraftLoweringError",
    "DraftSourceMap",
    "EXPERIMENT_DRAFT_JSON_SCHEMA",
    "EXPERIMENT_DRAFT_SCHEMA_ID",
    "ExperimentDraft",
    "ExperimentBuilder",
    "LoweredExperiment",
    "ProvenanceEntry",
    "ScientificMateriality",
    "RestrictedYamlError",
    "RestrictedYamlLimits",
    "SourceKind",
    "SourceLocation",
    "TemplateReference",
    "TEMPLATE_EXPANSION_LOCK_SCHEMA_ID",
    "TEMPLATE_DEFINITION_SCHEMA_ID",
    "TEMPLATE_AUTHORING_JSON_SCHEMA",
    "TEMPLATE_AUTHORING_SCHEMA_ID",
    "TemplateCatalog",
    "TemplateDefinition",
    "TemplateExpansion",
    "TemplateExpansionLock",
    "TemplateMigrationPolicy",
    "TemplateParameterTarget",
    "TemplateProfile",
    "TemplateSelection",
    "UnresolvedChoice",
    "UnresolvedKind",
    "WrittenAuthoringProject",
    "lower_experiment_draft",
    "builtin_templates",
    "create_template_draft",
    "expand_template",
    "load_yaml_experiment",
    "validate_authoring_provenance_payload",
    "validate_deployment_requirements_payload",
    "validate_experiment_draft_payload",
    "validate_template_authoring_payload",
    "parse_yaml_experiment",
    "read_yaml_experiment",
]
